### ISSUE TITLE
How can I give multiline body for Squash and Merge to master via github?

### ISSUE THREAD

**Issue by ansujohn** [conventional-changelog/standard-version#191]
I am merging develop branch (with multiple PRs merged to develop) to master branch via a Pull Request.

The PR desc follows the conventional-changelog of type(scope): desc.
I would like to add a body with details of fixes, features and so on.

Though I add the body in PR message body via github and in the Squash & Commit message body, it doesn't appear in CHANGELOG file.

How can I have a changelog as follows ??

Features
feature 1 desc
feature 2 desc
Fixes
Fix 1 desc
Fix 1 desc

Thanks for the help

**Comment by dubcdr** [comment]
bump

**Comment by stevemao** [comment]
body of commit messages are by default not included in the CHANGELOG since it is meant to be brief. You can click the commit link to view details. If you still want it included in CHANGELOG, you can't use this module directly. You'd have to use https://github.com/conventional-changelog/conventional-changelog and configure your [writer templates](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-writer)

**Comment by jbottigliero** [comment]
Closing this issue. 

It's very old at this point and the brief messages (commit title only) in the CHANGELOG is intended standard-version behavior.
