### ISSUE TITLE
Convenience feature: "Run .. to publish" message

### ISSUE THREAD

**Issue by dherges** [conventional-changelog/standard-version#193]
Can the ``Run `git push --follow-tags origin master` to publish`` message be improved? I am talking about this: https://github.com/conventional-changelog/standard-version/blob/master/lib/lifecycles/tag.js#L29-L32

Motivation: we work with an `upstream`-`origin` pattern and so I frequently have to run `git push --follow-tags upstream master`. 

Would it be possible to read the remote name of master branch and then print that?

**Comment by dherges** [comment]
Similar or related to #184, I guess.

**Comment by e-cloud** [comment]
I'm afraid it's less likely do so.

Since standard-version now support lifecycle hooks, if all your release steps are only with standard-version, you can define `posttag` script with `git push --follow-tags upstream master`. 

However, if it's not only with standard-version to do the release job, you'd better define a command in npm script like:
```json
{
  //...
  "scripts": {
    "release": "standard-version && do something else"
  }
  //...
}
```

**Comment by stevemao** [comment]
@dherges You said it's the same as #184. Let's continue discussing there :)
