### ISSUE TITLE
How is it different than `semantic-release`

### ISSUE THREAD

**Issue by sarbbottam** [conventional-changelog/standard-version#22]
I guess, [semantic-release](https://github.com/semantic-release/semantic-release) seems superior than this tool.

**Comment by nexdrew** [comment]
@sarbbottam Great question!

`semantic-release` is a fully automated library/system for versioning, changelog generation, git tagging, and publishing to the npm registry.

`standard-version` is different because it handles the versioning, changelog generation, and git tagging for you **without** automatic pushing (to GitHub) or publishing (to an npm registry). Use of `standard-version` only affects your local git repo - it doesn't affect remote resources at all. After you run `standard-version`, you still have to ability to review things and correct mistakes if you want to.

They are both based on the same foundation of structured commit messages (using [Angular format](https://github.com/bcoe/conventional-changelog-standard/blob/master/convention.md)), but `standard-version` is a good choice for folks who are not quite yet comfortable letting publishes go out automatically. In this way, you can view `standard-version` as an incremental step to adopting `semantic-release`.

Personally, I think they are both fantastic tools, and I encourage folks to use `semantic-release` over `standard-version` if it makes sense for them.

**Comment by sarbbottam** [comment]
Thanks!

**Comment by stevemao** [comment]
We could add this to the docs.
