### ISSUE TITLE
github pull request

### ISSUE THREAD

**Issue by benmonro** [conventional-changelog/standard-version#24]
I'm trying to use standard-version with a pull request.  We do PRs from a branch back to master on the same repo.  When I do this I choose squash commits, enter a 'standard-version- style commit message as the title, but I end up with a commit message that looks like this:

![image](https://cloud.githubusercontent.com/assets/399236/14800793/1896194c-0af9-11e6-8cdd-011594ac535f.png)

As a result, the change log never gets the features (other than the main one I typed in) that I added as part of the branch / PR.  Am I doing something wrong?

For reference I've created a simple repo to demonstrate what I'm talking about:
https://github.com/benmonro/stv-ex

**Comment by nexdrew** [comment]
@benmonro Good question!

Your workflow sounds correct per `standard-version` expectations, but the idea behind the default instructions is that **one PR equals, at most, one feature or fix**.

If (1) you're actually adding multiple features/fixes within a single PR and (2) each commit message is structured as such and (3) you want them all to end up in the CHANGELOG, then don't squash the commits when accepting the PR - just do a standard merge so that the commit history on your branch is preserved on `master` after the PR.

The problem with this approach is that your CHANGELOG won't map each commit to the PR that pulled it into `master` (because the commit messages don't reference the PR number). When commits are made, the PR might not even exist yet.

For this reason, we recommend (and `standard-version` assumes) keeping the scope of each PR to one general feature or fix. In practice, this allows you to use unstructured commit messages when committing each little change and then squashing them into a single commit with a structured message (referencing the PR number) once they have been reviewed and accepted.

Does that make sense? Any feedback?

**Comment by benmonro** [comment]
oh ok, yeah that makes perfect sense.  thanks!

**Comment by danielo515** [comment]
Expecting to split several one commit that you have been working on just to get a correct changelog is not being pragmatic. Sometimes you just fix more than one problem in one commit and they depend on each other, splitting them into multiple commits is a bad idea in many cases.
Please consider parsing several standard messages into one single commit
