### ISSUE TITLE
Possibility to provide a host type manually

### ISSUE THREAD

**Issue by klemenoslaj** [conventional-changelog/standard-version#306]
To my understanding currently `conventional-changelog` is detecting the host out of the `repository` value of `package.json`.

That alone is obviously not enough if git repo actually does not contain the host name.
_e.g. using **github** under `git.some-domain.com` will not be recognised correctly._

This means that anyone trying to use `standard-version` in a private repo, where usually the host is hidden from the url, will get an incorrect CHANGELOG.

QUESTION: Would it be ok to provide a `--host` flag which will be directly provided to the `conventionalChangelog` [here](https://github.com/conventional-changelog/standard-version/blob/69c62cfbddea7ce5e9b307f5167e20aee63a87da/lib/lifecycles/changelog.js#L32)?

**Comment by bcoe** [comment]
@klemenoslaj this is possible as of `standard-version@6.x.x` by overriding the `commitUrlFormat`, `compareUrlFormat`, `issueUrlFormat` and `userUrlFormat`, in a `.versionrc`.

I still might be open to adding `--host` and `--repo`, but you should at least be unblocked for now 👍

**Comment by klemenoslaj** [comment]
Thanks @bcoe for coming back to me! That indeed works :+1:

**Comment by klemenoslaj** [comment]
`--host` would be a welcome addition as well anyway. So feel free to re-open the issue if required.

**Comment by waterplea** [comment]
I have my repo located at `https://git.mycompany.com/projects/something/something/my-project`. And that is what I have under `repository` in my `package.json`. All worked fine in version 5, but I cannot override `issueUrlFormat` in v5 and I need to use something other than `issues` — I tried updating to 6 and it broke the links generation because my url only had host and no owner or repository, so it all turns into `https://git.mycompany.com///my-project`. Would be great to have an entire `repository` field from `package.json` available to Substitutions so I wouldn't have to duplicate it (and also `commitUrlFormat` and `compareUrlFormat` because they are also getting broken after upgrade to v6).
