### ISSUE TITLE
7.0.0 bumps patch version when features exist

### ISSUE THREAD

**Issue by jrparish** [conventional-changelog/standard-version#422]
After upgrading to 7.0.0, the patch version is being bumped when features exist in the commit list. 

Command I'm running:
`standard-version -a`

The changelog correctly sees the feature, but the bump is incorrect. 
![image](https://user-images.githubusercontent.com/5173987/62221252-f9cd3980-b376-11e9-9ceb-27351b18de48.png)

**Comment by bcoe** [comment]
This functionality was recommended by @coreyfarrell, see:

https://github.com/conventional-changelog/conventional-changelog/pull/452

I think it's reasonable, prior to a first major release, that a breaking change would be the minor bump, and a feature release the patch.

Personally I don't have a horse in this race, because I think it's best to go to `1.x.x` immediately, as behavior for SemVer pre 1.x is pretty poorly defined.

**Comment by jrparish** [comment]
I agree, but I didn't introduce a breaking change, just a normal feature. So I'd assume the minor would be bumped.

**Comment by jrparish** [comment]
Thank you, that link answers my question.
