### ISSUE TITLE
any thoughts about providing an undo command ?

### ISSUE THREAD

**Issue by lili21** [conventional-changelog/standard-version#520]
when the `standard-version` command runs into an error, it will leave the git in the staged state.
`CHANGELOG.md` and `package.json` file be changed and be added. but not commit with **the right** commit message.

in this situation, I'd like to undo the command, back to the state before I execute the `standard-version`.

**Comment by jbottigliero** [comment]
Hey, thanks for opening this issue! Rather than an "undo" I think the right approach here is to make `standard-version` atomic and rollback any changes if an error was encountered in `standard-version` lifecycles (see #528). 

I'm going to close this issue and we'll use #528 for tracking this functionality. If you feel this won't account for your use-case please feel free to leave a comment and reopen!

**Comment by nonara** [comment]
Presenting an alternate use-case here. If we fire with a wrong parameter (ie. wrong release type), no error occurs. In that case, undo would be nice. I've done that before and have had to manually remove the commits and tags several times.

What brought me here - I maintain a large multi-repo workspace. I used a new tool to execute a command on all yarn workspaces. Turns out it doesn't pass along my parameters, so `--dry-run` was ignored, and now I need to manually go into each repo and revert the changes.

In general, I understand your reasoning. Just wanted to point out that in case of user or tool error, undo could be helpful!

**Comment by jsudelko** [comment]
I agree with @nonara. Please consider reopening this issue. 

I've needed to undo `standard-version`''s work a few times before, and every single time it was because of user error, not a build tool failure. I'm here because I made a typo setting up scripts for a new(ish) repository, not a build error.
