### ISSUE TITLE
Multiple tags not supporting

### ISSUE THREAD

**Issue by creativemind1** [conventional-changelog/standard-version#562]
Hello,

I'm trying to give multiple tags with single merge to dev but I'm only getting the first tag support

```
feat(testing-branch): ‘Testing branch’

fix(fixing-branch): ‘Fixing branch’

chore(Aligning): ‘Chore testing’
```
Result:
### Features

* **testing-branch:** ‘Testing branch’ ([**#commentNo**](**URL**))

**Comment by khatastroffik** [comment]
afaik it's the standard.

Have a look at the [FAQ](https://github.com/conventional-changelog/standard-version#should-i-always-squash-commits-when-merging-prs):  what you're doing (many comments in 1 commit) is the same as squashing...

you should do:
```
commit -m "feat(testing-branch): ‘Testing branch’"
commit -m "fix(fixing-branch): ‘Fixing branch’"
commit -m "chore(Aligning): ‘Chore testing’"
```

**Comment by creativemind1** [comment]
No, I'm not committing here. I'm merging my PR after getting commits.

**Comment by khatastroffik** [comment]
> ... my PR after commits. ...

Each of your commits should contain a `feat:`, `fix:` ... prefixed comment as long as the feat, fix etc. are *completed*. Otherwise you'd use a neutral comment.
While your PR may list those prefixed comments as well (although not required), though *no changelog tool* will parse/use more than the first line (and the CHANGE BREAK) to generate different list items.

2 alternative **Best Practices** here, depending on your use case:

## 1 feature per 1 PR
```text
commit 1: "some work done on feat A" (note: no prefix here)
commit 2: "some more work done  on feat A" (note: no prefix here)
commit 3: "some final work  on feat A" <-- the feature A is completed here, but it's a neutral commment = no prefix here!
PR: "feat(A): allow the user to..." <-- PREFIX (optional: add all the comment above)
```
you could also do:
```text
...
commit 3: "feat(A): allow the user to..." <-- PREFIX the feature A is completed here (optional: add all the comment above)
PR: "Please review the features A" <-- neutral comment (no need for more description here, no prefix here)
```

## multiple features per 1 PR
```text
commit 1: "feat(X): add function X" <-- PREFIX the feature X is completed here !
commit 2: "feat(Y): add function Y" <-- PREFIX the feature Y is completed here !
commit 1: "feat(Z): add function Z" <-- PREFIX the feature Z is completed here !
PR: "Please review the features X, Y and Z" <-- neutral comment (optional: add all the comments above) (note: no prefix here)
```

The important things:
- use the prefixes only once (!) per feature, fix etc...
- extended description in comments (starting with second line) won't be parsed to add new changelog items (but to mark a "breaking change" if any).

**Comment by creativemind1** [comment]
Thanks very good explanations.

With regards to last neutral comment about "multiple features per 1 PR", if I go with that way and merge, I will have to use merge strategy as  "Merge Commit" and not Squash right?

**Comment by khatastroffik** [comment]
You may do both ;-)
I would go for "merge commit" if I'm concerned of tracking (1 feat = 1 commit) the features individually e.g. to target them in case of a CR or a support request later. The comments will also stay visible individually.
Using squash commit would work as well, though the comments would then be stacked all together and the original single commits would not be visible.

I do favor the "_merge commit_" :)

Note 1: squash is useful e.g. in case of a feature branch where you're commiting all the work-in-progress steps and at the end want to have 1 "summary" commit for the finalized feature.  All "steps" comments will appear in the body of the summary commit comment instead of individually.

Note 2: Are you aware of the "**[git-flow](https://nvie.com/posts/a-successful-git-branching-model/)**" workflow handling "features" branch, merges, PRs? I often use this workflow in my projects: 
- works well with teams (in particular whith not so experienced team members)
- nativelly supported by "[SourceTree](https://sourcetreeapp.com/)" (windows/mac app) as demoed [here](https://www.bogotobogo.com/cplusplus/Git/Git_GitHub_Source_Tree_3_Git_WorkFlow.php)
- works with all git repos (GHub, GLab BBucket)

Hence git-flow is a kind of a KISS tool ;-) (see [gf tutorial](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow))

**Comment by creativemind1** [comment]
I will go through GIT Flow., just like a question if you can answer that as well. Is there any way I can reset all my tags I have committed so far in ignorance for testing?

**Comment by khatastroffik** [comment]
Not sure I understand your question correctly...
you mean deleting all **tags** as e.g. "v1.0.0", "v1.0.1", "v1.0.2", "v1.1.0" etc. ?
then you'd give [How to remove all git origin and local tags?](https://stackoverflow.com/questions/44702757/how-to-remove-all-git-origin-and-local-tags) a try ;-)

**Comment by creativemind1** [comment]
Oh wow thanks :)
