### ISSUE TITLE
How can I generate a changelog from main when my default git branch is develop?

### ISSUE THREAD

**Issue by Celtech** [conventional-changelog/standard-version#961]
At work our default git branch is `develop`, however we still merge to main after develop and deploy from main. During changelog generation how do I make it compare against main instead of develop without switching my default branch?

I.e

- I make a tag 1.0.0 from main
- My next release is 1.0.1 also from main

How do I make it so the changelog generates between those 2 versions and pulls the changes in them from main instead of develop?

**Comment by TimothyJones** [comment]
I think the tool just works on the current branch, not the default branch- does switching branches work for you?Sent from my mobileOn 4 Apr 2024, at 15:47, Tim Hinz ***@***.***> wrote:﻿
At work our default git branch is develop, however we still merge to main after develop and deploy from main. During changelog generation how do I make it compare against main instead of develop without switching my default branch?
I.e

I make a tag 1.0.0 from main
My next release is 1.0.1 also from main

How do I make it so the changelog generates between those 2 versions and pulls the changes in them from main instead of develop?

**Comment by Celtech** [comment]
@TimothyJones it doesn't seem to no, if I run it on my current feature branch which was made from develop against tag 1.0.0 which was made from main, I get a changelog of the entire history generated. However if I make a tag from develop, and run it against that, I get no changelog generated.

**Comment by Celtech** [comment]
Edit im dumb, ignore me, you were right. It does use the current branch. Closed!
